// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "canhrActi_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// classify_intensity_cpp
IntegerVector classify_intensity_cpp(NumericVector counts, int sedentary_threshold, int light_threshold, int moderate_threshold, int vigorous_threshold);
RcppExport SEXP _canhrActi_classify_intensity_cpp(SEXP countsSEXP, SEXP sedentary_thresholdSEXP, SEXP light_thresholdSEXP, SEXP moderate_thresholdSEXP, SEXP vigorous_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type sedentary_threshold(sedentary_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type light_threshold(light_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type moderate_threshold(moderate_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type vigorous_threshold(vigorous_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(classify_intensity_cpp(counts, sedentary_threshold, light_threshold, moderate_threshold, vigorous_threshold));
    return rcpp_result_gen;
END_RCPP
}
// detect_mvpa_bouts_cpp
Rcpp::List detect_mvpa_bouts_cpp(NumericVector counts, int moderate_threshold, int min_bout_length, int drop_time, bool use_80_percent_rule);
RcppExport SEXP _canhrActi_detect_mvpa_bouts_cpp(SEXP countsSEXP, SEXP moderate_thresholdSEXP, SEXP min_bout_lengthSEXP, SEXP drop_timeSEXP, SEXP use_80_percent_ruleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type moderate_threshold(moderate_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_bout_length(min_bout_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type drop_time(drop_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_80_percent_rule(use_80_percent_ruleSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_mvpa_bouts_cpp(counts, moderate_threshold, min_bout_length, drop_time, use_80_percent_rule));
    return rcpp_result_gen;
END_RCPP
}
// detect_sedentary_bouts_cpp
Rcpp::List detect_sedentary_bouts_cpp(NumericVector counts, int sedentary_threshold, int min_bout_length, IntegerVector wear);
RcppExport SEXP _canhrActi_detect_sedentary_bouts_cpp(SEXP countsSEXP, SEXP sedentary_thresholdSEXP, SEXP min_bout_lengthSEXP, SEXP wearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type sedentary_threshold(sedentary_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_bout_length(min_bout_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_sedentary_bouts_cpp(counts, sedentary_threshold, min_bout_length, wear));
    return rcpp_result_gen;
END_RCPP
}
// calculate_transition_probabilities_cpp
Rcpp::List calculate_transition_probabilities_cpp(NumericVector counts, int sedentary_threshold, IntegerVector wear);
RcppExport SEXP _canhrActi_calculate_transition_probabilities_cpp(SEXP countsSEXP, SEXP sedentary_thresholdSEXP, SEXP wearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type sedentary_threshold(sedentary_thresholdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_transition_probabilities_cpp(counts, sedentary_threshold, wear));
    return rcpp_result_gen;
END_RCPP
}
// calculate_w50_cpp
double calculate_w50_cpp(IntegerVector bout_lengths);
RcppExport SEXP _canhrActi_calculate_w50_cpp(SEXP bout_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bout_lengths(bout_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_w50_cpp(bout_lengths));
    return rcpp_result_gen;
END_RCPP
}
// calculate_gini_cpp
double calculate_gini_cpp(IntegerVector bout_lengths);
RcppExport SEXP _canhrActi_calculate_gini_cpp(SEXP bout_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bout_lengths(bout_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_gini_cpp(bout_lengths));
    return rcpp_result_gen;
END_RCPP
}
// calculate_alpha_robust_cpp
Rcpp::List calculate_alpha_robust_cpp(IntegerVector bout_lengths, int xmin);
RcppExport SEXP _canhrActi_calculate_alpha_robust_cpp(SEXP bout_lengthsSEXP, SEXP xminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bout_lengths(bout_lengthsSEXP);
    Rcpp::traits::input_parameter< int >::type xmin(xminSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_alpha_robust_cpp(bout_lengths, xmin));
    return rcpp_result_gen;
END_RCPP
}
// estimate_xmin_cpp
Rcpp::List estimate_xmin_cpp(IntegerVector bout_lengths);
RcppExport SEXP _canhrActi_estimate_xmin_cpp(SEXP bout_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bout_lengths(bout_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_xmin_cpp(bout_lengths));
    return rcpp_result_gen;
END_RCPP
}
// sedentary_fragmentation_all_cpp
Rcpp::List sedentary_fragmentation_all_cpp(NumericVector counts, int sedentary_threshold, IntegerVector wear);
RcppExport SEXP _canhrActi_sedentary_fragmentation_all_cpp(SEXP countsSEXP, SEXP sedentary_thresholdSEXP, SEXP wearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type sedentary_threshold(sedentary_thresholdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    rcpp_result_gen = Rcpp::wrap(sedentary_fragmentation_all_cpp(counts, sedentary_threshold, wear));
    return rcpp_result_gen;
END_RCPP
}
// bout_summary_by_day_cpp
Rcpp::DataFrame bout_summary_by_day_cpp(NumericVector counts, IntegerVector day_indices, int sedentary_threshold, int moderate_threshold);
RcppExport SEXP _canhrActi_bout_summary_by_day_cpp(SEXP countsSEXP, SEXP day_indicesSEXP, SEXP sedentary_thresholdSEXP, SEXP moderate_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type day_indices(day_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type sedentary_threshold(sedentary_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type moderate_threshold(moderate_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(bout_summary_by_day_cpp(counts, day_indices, sedentary_threshold, moderate_threshold));
    return rcpp_result_gen;
END_RCPP
}
// intensity_gradient_cpp
Rcpp::List intensity_gradient_cpp(NumericVector data, double epoch_length, double bin_size, double max_value);
RcppExport SEXP _canhrActi_intensity_gradient_cpp(SEXP dataSEXP, SEXP epoch_lengthSEXP, SEXP bin_sizeSEXP, SEXP max_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type epoch_length(epoch_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type bin_size(bin_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_value(max_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(intensity_gradient_cpp(data, epoch_length, bin_size, max_value));
    return rcpp_result_gen;
END_RCPP
}
// calculate_MX_cpp
Rcpp::List calculate_MX_cpp(NumericVector data, IntegerVector X_values, double epoch_length);
RcppExport SEXP _canhrActi_calculate_MX_cpp(SEXP dataSEXP, SEXP X_valuesSEXP, SEXP epoch_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X_values(X_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type epoch_length(epoch_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_MX_cpp(data, X_values, epoch_length));
    return rcpp_result_gen;
END_RCPP
}
// activity_profile_cpp
Rcpp::List activity_profile_cpp(NumericVector data, double epoch_length, double bin_size, IntegerVector X_values);
RcppExport SEXP _canhrActi_activity_profile_cpp(SEXP dataSEXP, SEXP epoch_lengthSEXP, SEXP bin_sizeSEXP, SEXP X_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type epoch_length(epoch_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type bin_size(bin_sizeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X_values(X_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(activity_profile_cpp(data, epoch_length, bin_size, X_values));
    return rcpp_result_gen;
END_RCPP
}
// acceleration_histogram_cpp
Rcpp::DataFrame acceleration_histogram_cpp(NumericVector data, double bin_size, double max_value);
RcppExport SEXP _canhrActi_acceleration_histogram_cpp(SEXP dataSEXP, SEXP bin_sizeSEXP, SEXP max_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type bin_size(bin_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_value(max_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(acceleration_histogram_cpp(data, bin_size, max_value));
    return rcpp_result_gen;
END_RCPP
}
// acceleration_percentiles_cpp
NumericVector acceleration_percentiles_cpp(NumericVector data, NumericVector probs);
RcppExport SEXP _canhrActi_acceleration_percentiles_cpp(SEXP dataSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(acceleration_percentiles_cpp(data, probs));
    return rcpp_result_gen;
END_RCPP
}
// cole_kripke_cpp
IntegerVector cole_kripke_cpp(NumericVector counts, double threshold, bool apply_rescoring);
RcppExport SEXP _canhrActi_cole_kripke_cpp(SEXP countsSEXP, SEXP thresholdSEXP, SEXP apply_rescoringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type apply_rescoring(apply_rescoringSEXP);
    rcpp_result_gen = Rcpp::wrap(cole_kripke_cpp(counts, threshold, apply_rescoring));
    return rcpp_result_gen;
END_RCPP
}
// webster_rescoring_cpp
IntegerVector webster_rescoring_cpp(IntegerVector sleep);
RcppExport SEXP _canhrActi_webster_rescoring_cpp(SEXP sleepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sleep(sleepSEXP);
    rcpp_result_gen = Rcpp::wrap(webster_rescoring_cpp(sleep));
    return rcpp_result_gen;
END_RCPP
}
// sadeh_cpp
IntegerVector sadeh_cpp(NumericVector counts, double threshold);
RcppExport SEXP _canhrActi_sadeh_cpp(SEXP countsSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(sadeh_cpp(counts, threshold));
    return rcpp_result_gen;
END_RCPP
}
// tudor_locke_cpp
IntegerVector tudor_locke_cpp(NumericVector counts, int sleep_threshold, int min_sleep_block, int max_wake_block);
RcppExport SEXP _canhrActi_tudor_locke_cpp(SEXP countsSEXP, SEXP sleep_thresholdSEXP, SEXP min_sleep_blockSEXP, SEXP max_wake_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type sleep_threshold(sleep_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_sleep_block(min_sleep_blockSEXP);
    Rcpp::traits::input_parameter< int >::type max_wake_block(max_wake_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(tudor_locke_cpp(counts, sleep_threshold, min_sleep_block, max_wake_block));
    return rcpp_result_gen;
END_RCPP
}
// detect_sleep_period_cpp
Rcpp::List detect_sleep_period_cpp(IntegerVector sleep, int min_sleep_duration, int sleep_onset_buffer, int wake_buffer);
RcppExport SEXP _canhrActi_detect_sleep_period_cpp(SEXP sleepSEXP, SEXP min_sleep_durationSEXP, SEXP sleep_onset_bufferSEXP, SEXP wake_bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sleep(sleepSEXP);
    Rcpp::traits::input_parameter< int >::type min_sleep_duration(min_sleep_durationSEXP);
    Rcpp::traits::input_parameter< int >::type sleep_onset_buffer(sleep_onset_bufferSEXP);
    Rcpp::traits::input_parameter< int >::type wake_buffer(wake_bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_sleep_period_cpp(sleep, min_sleep_duration, sleep_onset_buffer, wake_buffer));
    return rcpp_result_gen;
END_RCPP
}
// calculate_sleep_metrics_cpp
Rcpp::List calculate_sleep_metrics_cpp(IntegerVector sleep, int sleep_onset, int wake_time);
RcppExport SEXP _canhrActi_calculate_sleep_metrics_cpp(SEXP sleepSEXP, SEXP sleep_onsetSEXP, SEXP wake_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sleep(sleepSEXP);
    Rcpp::traits::input_parameter< int >::type sleep_onset(sleep_onsetSEXP);
    Rcpp::traits::input_parameter< int >::type wake_time(wake_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_sleep_metrics_cpp(sleep, sleep_onset, wake_time));
    return rcpp_result_gen;
END_RCPP
}
// calculate_sri_cpp
double calculate_sri_cpp(IntegerMatrix sleep_matrix);
RcppExport SEXP _canhrActi_calculate_sri_cpp(SEXP sleep_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type sleep_matrix(sleep_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_sri_cpp(sleep_matrix));
    return rcpp_result_gen;
END_RCPP
}
// calculate_sri_vector_cpp
double calculate_sri_vector_cpp(IntegerVector sleep, int epochs_per_day);
RcppExport SEXP _canhrActi_calculate_sri_vector_cpp(SEXP sleepSEXP, SEXP epochs_per_daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sleep(sleepSEXP);
    Rcpp::traits::input_parameter< int >::type epochs_per_day(epochs_per_daySEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_sri_vector_cpp(sleep, epochs_per_day));
    return rcpp_result_gen;
END_RCPP
}
// sleep_summary_by_night_cpp
Rcpp::DataFrame sleep_summary_by_night_cpp(IntegerVector sleep, IntegerVector night_indices, NumericVector counts);
RcppExport SEXP _canhrActi_sleep_summary_by_night_cpp(SEXP sleepSEXP, SEXP night_indicesSEXP, SEXP countsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sleep(sleepSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type night_indices(night_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    rcpp_result_gen = Rcpp::wrap(sleep_summary_by_night_cpp(sleep, night_indices, counts));
    return rcpp_result_gen;
END_RCPP
}
// sliding_window_mean_cpp
Rcpp::List sliding_window_mean_cpp(NumericVector x, int window_size);
RcppExport SEXP _canhrActi_sliding_window_mean_cpp(SEXP xSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sliding_window_mean_cpp(x, window_size));
    return rcpp_result_gen;
END_RCPP
}
// calculate_L5_M10_cpp
Rcpp::List calculate_L5_M10_cpp(NumericVector minute_data, int window_L5, int window_M10, int start_minute);
RcppExport SEXP _canhrActi_calculate_L5_M10_cpp(SEXP minute_dataSEXP, SEXP window_L5SEXP, SEXP window_M10SEXP, SEXP start_minuteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    Rcpp::traits::input_parameter< int >::type window_L5(window_L5SEXP);
    Rcpp::traits::input_parameter< int >::type window_M10(window_M10SEXP);
    Rcpp::traits::input_parameter< int >::type start_minute(start_minuteSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_L5_M10_cpp(minute_data, window_L5, window_M10, start_minute));
    return rcpp_result_gen;
END_RCPP
}
// calculate_L1_M1_cpp
Rcpp::List calculate_L1_M1_cpp(NumericVector minute_data);
RcppExport SEXP _canhrActi_calculate_L1_M1_cpp(SEXP minute_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_L1_M1_cpp(minute_data));
    return rcpp_result_gen;
END_RCPP
}
// calculate_IS_cpp
double calculate_IS_cpp(NumericVector hourly_data, int hours_per_day);
RcppExport SEXP _canhrActi_calculate_IS_cpp(SEXP hourly_dataSEXP, SEXP hours_per_daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type hourly_data(hourly_dataSEXP);
    Rcpp::traits::input_parameter< int >::type hours_per_day(hours_per_daySEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_IS_cpp(hourly_data, hours_per_day));
    return rcpp_result_gen;
END_RCPP
}
// calculate_IV_cpp
double calculate_IV_cpp(NumericVector hourly_data);
RcppExport SEXP _canhrActi_calculate_IV_cpp(SEXP hourly_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type hourly_data(hourly_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_IV_cpp(hourly_data));
    return rcpp_result_gen;
END_RCPP
}
// calculate_phi_cpp
double calculate_phi_cpp(NumericVector x, int lag);
RcppExport SEXP _canhrActi_calculate_phi_cpp(SEXP xSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_phi_cpp(x, lag));
    return rcpp_result_gen;
END_RCPP
}
// rolling_mean_cpp
NumericVector rolling_mean_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_mean_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_mean_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sd_cpp
NumericVector rolling_sd_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_sd_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sd_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sum_cpp
NumericVector rolling_sum_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_sum_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sum_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_max_cpp
NumericVector rolling_max_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_max_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_max_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_min_cpp
NumericVector rolling_min_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_min_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_min_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// calculate_all_circadian_cpp
Rcpp::List calculate_all_circadian_cpp(NumericVector minute_data, int hours_per_day, int start_minute);
RcppExport SEXP _canhrActi_calculate_all_circadian_cpp(SEXP minute_dataSEXP, SEXP hours_per_daySEXP, SEXP start_minuteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    Rcpp::traits::input_parameter< int >::type hours_per_day(hours_per_daySEXP);
    Rcpp::traits::input_parameter< int >::type start_minute(start_minuteSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_all_circadian_cpp(minute_data, hours_per_day, start_minute));
    return rcpp_result_gen;
END_RCPP
}
// detect_wear_core_cpp
IntegerVector detect_wear_core_cpp(NumericVector counts, int window_minutes, int spike_tolerance_minutes, int spike_max_count, bool use_upstream_downstream, int upstream_minutes, int downstream_minutes);
RcppExport SEXP _canhrActi_detect_wear_core_cpp(SEXP countsSEXP, SEXP window_minutesSEXP, SEXP spike_tolerance_minutesSEXP, SEXP spike_max_countSEXP, SEXP use_upstream_downstreamSEXP, SEXP upstream_minutesSEXP, SEXP downstream_minutesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type window_minutes(window_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_tolerance_minutes(spike_tolerance_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_max_count(spike_max_countSEXP);
    Rcpp::traits::input_parameter< bool >::type use_upstream_downstream(use_upstream_downstreamSEXP);
    Rcpp::traits::input_parameter< int >::type upstream_minutes(upstream_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type downstream_minutes(downstream_minutesSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_wear_core_cpp(counts, window_minutes, spike_tolerance_minutes, spike_max_count, use_upstream_downstream, upstream_minutes, downstream_minutes));
    return rcpp_result_gen;
END_RCPP
}
// wear_troiano_cpp
IntegerVector wear_troiano_cpp(NumericVector counts, int window_minutes, int spike_tolerance, int spike_max_count);
RcppExport SEXP _canhrActi_wear_troiano_cpp(SEXP countsSEXP, SEXP window_minutesSEXP, SEXP spike_toleranceSEXP, SEXP spike_max_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type window_minutes(window_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_tolerance(spike_toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type spike_max_count(spike_max_countSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_troiano_cpp(counts, window_minutes, spike_tolerance, spike_max_count));
    return rcpp_result_gen;
END_RCPP
}
// wear_choi_cpp
IntegerVector wear_choi_cpp(NumericVector counts, int window_minutes, int spike_tolerance, int spike_max_count, int upstream_minutes, int downstream_minutes);
RcppExport SEXP _canhrActi_wear_choi_cpp(SEXP countsSEXP, SEXP window_minutesSEXP, SEXP spike_toleranceSEXP, SEXP spike_max_countSEXP, SEXP upstream_minutesSEXP, SEXP downstream_minutesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type window_minutes(window_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_tolerance(spike_toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type spike_max_count(spike_max_countSEXP);
    Rcpp::traits::input_parameter< int >::type upstream_minutes(upstream_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type downstream_minutes(downstream_minutesSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_choi_cpp(counts, window_minutes, spike_tolerance, spike_max_count, upstream_minutes, downstream_minutes));
    return rcpp_result_gen;
END_RCPP
}
// wear_canhr2025_cpp
IntegerVector wear_canhr2025_cpp(NumericVector counts, int window_minutes, int spike_tolerance, int spike_max_count, int upstream_minutes, int downstream_minutes);
RcppExport SEXP _canhrActi_wear_canhr2025_cpp(SEXP countsSEXP, SEXP window_minutesSEXP, SEXP spike_toleranceSEXP, SEXP spike_max_countSEXP, SEXP upstream_minutesSEXP, SEXP downstream_minutesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type window_minutes(window_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_tolerance(spike_toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type spike_max_count(spike_max_countSEXP);
    Rcpp::traits::input_parameter< int >::type upstream_minutes(upstream_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type downstream_minutes(downstream_minutesSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_canhr2025_cpp(counts, window_minutes, spike_tolerance, spike_max_count, upstream_minutes, downstream_minutes));
    return rcpp_result_gen;
END_RCPP
}
// wear_triaxial_cpp
IntegerVector wear_triaxial_cpp(NumericVector axis1, NumericVector axis2, NumericVector axis3, int window_minutes, int spike_tolerance, double sd_threshold);
RcppExport SEXP _canhrActi_wear_triaxial_cpp(SEXP axis1SEXP, SEXP axis2SEXP, SEXP axis3SEXP, SEXP window_minutesSEXP, SEXP spike_toleranceSEXP, SEXP sd_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type axis1(axis1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type axis2(axis2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type axis3(axis3SEXP);
    Rcpp::traits::input_parameter< int >::type window_minutes(window_minutesSEXP);
    Rcpp::traits::input_parameter< int >::type spike_tolerance(spike_toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type sd_threshold(sd_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_triaxial_cpp(axis1, axis2, axis3, window_minutes, spike_tolerance, sd_threshold));
    return rcpp_result_gen;
END_RCPP
}
// wear_summary_cpp
Rcpp::List wear_summary_cpp(IntegerVector wear, int epochs_per_hour, int min_wear_hours);
RcppExport SEXP _canhrActi_wear_summary_cpp(SEXP wearSEXP, SEXP epochs_per_hourSEXP, SEXP min_wear_hoursSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    Rcpp::traits::input_parameter< int >::type epochs_per_hour(epochs_per_hourSEXP);
    Rcpp::traits::input_parameter< int >::type min_wear_hours(min_wear_hoursSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_summary_cpp(wear, epochs_per_hour, min_wear_hours));
    return rcpp_result_gen;
END_RCPP
}
// get_wear_periods_cpp
Rcpp::DataFrame get_wear_periods_cpp(IntegerVector wear, int min_duration_epochs);
RcppExport SEXP _canhrActi_get_wear_periods_cpp(SEXP wearSEXP, SEXP min_duration_epochsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    Rcpp::traits::input_parameter< int >::type min_duration_epochs(min_duration_epochsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_wear_periods_cpp(wear, min_duration_epochs));
    return rcpp_result_gen;
END_RCPP
}
// wear_by_day_cpp
Rcpp::DataFrame wear_by_day_cpp(IntegerVector wear, IntegerVector day_indices, int epochs_per_hour, int min_wear_hours);
RcppExport SEXP _canhrActi_wear_by_day_cpp(SEXP wearSEXP, SEXP day_indicesSEXP, SEXP epochs_per_hourSEXP, SEXP min_wear_hoursSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type wear(wearSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type day_indices(day_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type epochs_per_hour(epochs_per_hourSEXP);
    Rcpp::traits::input_parameter< int >::type min_wear_hours(min_wear_hoursSEXP);
    rcpp_result_gen = Rcpp::wrap(wear_by_day_cpp(wear, day_indices, epochs_per_hour, min_wear_hours));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_canhrActi_classify_intensity_cpp", (DL_FUNC) &_canhrActi_classify_intensity_cpp, 5},
    {"_canhrActi_detect_mvpa_bouts_cpp", (DL_FUNC) &_canhrActi_detect_mvpa_bouts_cpp, 5},
    {"_canhrActi_detect_sedentary_bouts_cpp", (DL_FUNC) &_canhrActi_detect_sedentary_bouts_cpp, 4},
    {"_canhrActi_calculate_transition_probabilities_cpp", (DL_FUNC) &_canhrActi_calculate_transition_probabilities_cpp, 3},
    {"_canhrActi_calculate_w50_cpp", (DL_FUNC) &_canhrActi_calculate_w50_cpp, 1},
    {"_canhrActi_calculate_gini_cpp", (DL_FUNC) &_canhrActi_calculate_gini_cpp, 1},
    {"_canhrActi_calculate_alpha_robust_cpp", (DL_FUNC) &_canhrActi_calculate_alpha_robust_cpp, 2},
    {"_canhrActi_estimate_xmin_cpp", (DL_FUNC) &_canhrActi_estimate_xmin_cpp, 1},
    {"_canhrActi_sedentary_fragmentation_all_cpp", (DL_FUNC) &_canhrActi_sedentary_fragmentation_all_cpp, 3},
    {"_canhrActi_bout_summary_by_day_cpp", (DL_FUNC) &_canhrActi_bout_summary_by_day_cpp, 4},
    {"_canhrActi_intensity_gradient_cpp", (DL_FUNC) &_canhrActi_intensity_gradient_cpp, 4},
    {"_canhrActi_calculate_MX_cpp", (DL_FUNC) &_canhrActi_calculate_MX_cpp, 3},
    {"_canhrActi_activity_profile_cpp", (DL_FUNC) &_canhrActi_activity_profile_cpp, 4},
    {"_canhrActi_acceleration_histogram_cpp", (DL_FUNC) &_canhrActi_acceleration_histogram_cpp, 3},
    {"_canhrActi_acceleration_percentiles_cpp", (DL_FUNC) &_canhrActi_acceleration_percentiles_cpp, 2},
    {"_canhrActi_cole_kripke_cpp", (DL_FUNC) &_canhrActi_cole_kripke_cpp, 3},
    {"_canhrActi_webster_rescoring_cpp", (DL_FUNC) &_canhrActi_webster_rescoring_cpp, 1},
    {"_canhrActi_sadeh_cpp", (DL_FUNC) &_canhrActi_sadeh_cpp, 2},
    {"_canhrActi_tudor_locke_cpp", (DL_FUNC) &_canhrActi_tudor_locke_cpp, 4},
    {"_canhrActi_detect_sleep_period_cpp", (DL_FUNC) &_canhrActi_detect_sleep_period_cpp, 4},
    {"_canhrActi_calculate_sleep_metrics_cpp", (DL_FUNC) &_canhrActi_calculate_sleep_metrics_cpp, 3},
    {"_canhrActi_calculate_sri_cpp", (DL_FUNC) &_canhrActi_calculate_sri_cpp, 1},
    {"_canhrActi_calculate_sri_vector_cpp", (DL_FUNC) &_canhrActi_calculate_sri_vector_cpp, 2},
    {"_canhrActi_sleep_summary_by_night_cpp", (DL_FUNC) &_canhrActi_sleep_summary_by_night_cpp, 3},
    {"_canhrActi_sliding_window_mean_cpp", (DL_FUNC) &_canhrActi_sliding_window_mean_cpp, 2},
    {"_canhrActi_calculate_L5_M10_cpp", (DL_FUNC) &_canhrActi_calculate_L5_M10_cpp, 4},
    {"_canhrActi_calculate_L1_M1_cpp", (DL_FUNC) &_canhrActi_calculate_L1_M1_cpp, 1},
    {"_canhrActi_calculate_IS_cpp", (DL_FUNC) &_canhrActi_calculate_IS_cpp, 2},
    {"_canhrActi_calculate_IV_cpp", (DL_FUNC) &_canhrActi_calculate_IV_cpp, 1},
    {"_canhrActi_calculate_phi_cpp", (DL_FUNC) &_canhrActi_calculate_phi_cpp, 2},
    {"_canhrActi_rolling_mean_cpp", (DL_FUNC) &_canhrActi_rolling_mean_cpp, 2},
    {"_canhrActi_rolling_sd_cpp", (DL_FUNC) &_canhrActi_rolling_sd_cpp, 2},
    {"_canhrActi_rolling_sum_cpp", (DL_FUNC) &_canhrActi_rolling_sum_cpp, 2},
    {"_canhrActi_rolling_max_cpp", (DL_FUNC) &_canhrActi_rolling_max_cpp, 2},
    {"_canhrActi_rolling_min_cpp", (DL_FUNC) &_canhrActi_rolling_min_cpp, 2},
    {"_canhrActi_calculate_all_circadian_cpp", (DL_FUNC) &_canhrActi_calculate_all_circadian_cpp, 3},
    {"_canhrActi_detect_wear_core_cpp", (DL_FUNC) &_canhrActi_detect_wear_core_cpp, 7},
    {"_canhrActi_wear_troiano_cpp", (DL_FUNC) &_canhrActi_wear_troiano_cpp, 4},
    {"_canhrActi_wear_choi_cpp", (DL_FUNC) &_canhrActi_wear_choi_cpp, 6},
    {"_canhrActi_wear_canhr2025_cpp", (DL_FUNC) &_canhrActi_wear_canhr2025_cpp, 6},
    {"_canhrActi_wear_triaxial_cpp", (DL_FUNC) &_canhrActi_wear_triaxial_cpp, 6},
    {"_canhrActi_wear_summary_cpp", (DL_FUNC) &_canhrActi_wear_summary_cpp, 3},
    {"_canhrActi_get_wear_periods_cpp", (DL_FUNC) &_canhrActi_get_wear_periods_cpp, 2},
    {"_canhrActi_wear_by_day_cpp", (DL_FUNC) &_canhrActi_wear_by_day_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_canhrActi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
