// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sliding_window_mean_cpp
Rcpp::List sliding_window_mean_cpp(NumericVector x, int window_size);
RcppExport SEXP _canhrActi_sliding_window_mean_cpp(SEXP xSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sliding_window_mean_cpp(x, window_size));
    return rcpp_result_gen;
END_RCPP
}
// calculate_L5_M10_cpp
Rcpp::List calculate_L5_M10_cpp(NumericVector minute_data, int window_L5, int window_M10, int start_minute);
RcppExport SEXP _canhrActi_calculate_L5_M10_cpp(SEXP minute_dataSEXP, SEXP window_L5SEXP, SEXP window_M10SEXP, SEXP start_minuteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    Rcpp::traits::input_parameter< int >::type window_L5(window_L5SEXP);
    Rcpp::traits::input_parameter< int >::type window_M10(window_M10SEXP);
    Rcpp::traits::input_parameter< int >::type start_minute(start_minuteSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_L5_M10_cpp(minute_data, window_L5, window_M10, start_minute));
    return rcpp_result_gen;
END_RCPP
}
// calculate_L1_M1_cpp
Rcpp::List calculate_L1_M1_cpp(NumericVector minute_data);
RcppExport SEXP _canhrActi_calculate_L1_M1_cpp(SEXP minute_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_L1_M1_cpp(minute_data));
    return rcpp_result_gen;
END_RCPP
}
// calculate_IS_cpp
double calculate_IS_cpp(NumericVector hourly_data, int hours_per_day);
RcppExport SEXP _canhrActi_calculate_IS_cpp(SEXP hourly_dataSEXP, SEXP hours_per_daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type hourly_data(hourly_dataSEXP);
    Rcpp::traits::input_parameter< int >::type hours_per_day(hours_per_daySEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_IS_cpp(hourly_data, hours_per_day));
    return rcpp_result_gen;
END_RCPP
}
// calculate_IV_cpp
double calculate_IV_cpp(NumericVector hourly_data);
RcppExport SEXP _canhrActi_calculate_IV_cpp(SEXP hourly_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type hourly_data(hourly_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_IV_cpp(hourly_data));
    return rcpp_result_gen;
END_RCPP
}
// calculate_phi_cpp
double calculate_phi_cpp(NumericVector x, int lag);
RcppExport SEXP _canhrActi_calculate_phi_cpp(SEXP xSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_phi_cpp(x, lag));
    return rcpp_result_gen;
END_RCPP
}
// rolling_mean_cpp
NumericVector rolling_mean_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_mean_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_mean_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sd_cpp
NumericVector rolling_sd_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_sd_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sd_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sum_cpp
NumericVector rolling_sum_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_sum_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sum_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_max_cpp
NumericVector rolling_max_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_max_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_max_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// rolling_min_cpp
NumericVector rolling_min_cpp(NumericVector x, int window);
RcppExport SEXP _canhrActi_rolling_min_cpp(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_min_cpp(x, window));
    return rcpp_result_gen;
END_RCPP
}
// calculate_all_circadian_cpp
Rcpp::List calculate_all_circadian_cpp(NumericVector minute_data, int hours_per_day, int start_minute);
RcppExport SEXP _canhrActi_calculate_all_circadian_cpp(SEXP minute_dataSEXP, SEXP hours_per_daySEXP, SEXP start_minuteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type minute_data(minute_dataSEXP);
    Rcpp::traits::input_parameter< int >::type hours_per_day(hours_per_daySEXP);
    Rcpp::traits::input_parameter< int >::type start_minute(start_minuteSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_all_circadian_cpp(minute_data, hours_per_day, start_minute));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_canhrActi_sliding_window_mean_cpp", (DL_FUNC) &_canhrActi_sliding_window_mean_cpp, 2},
    {"_canhrActi_calculate_L5_M10_cpp", (DL_FUNC) &_canhrActi_calculate_L5_M10_cpp, 4},
    {"_canhrActi_calculate_L1_M1_cpp", (DL_FUNC) &_canhrActi_calculate_L1_M1_cpp, 1},
    {"_canhrActi_calculate_IS_cpp", (DL_FUNC) &_canhrActi_calculate_IS_cpp, 2},
    {"_canhrActi_calculate_IV_cpp", (DL_FUNC) &_canhrActi_calculate_IV_cpp, 1},
    {"_canhrActi_calculate_phi_cpp", (DL_FUNC) &_canhrActi_calculate_phi_cpp, 2},
    {"_canhrActi_rolling_mean_cpp", (DL_FUNC) &_canhrActi_rolling_mean_cpp, 2},
    {"_canhrActi_rolling_sd_cpp", (DL_FUNC) &_canhrActi_rolling_sd_cpp, 2},
    {"_canhrActi_rolling_sum_cpp", (DL_FUNC) &_canhrActi_rolling_sum_cpp, 2},
    {"_canhrActi_rolling_max_cpp", (DL_FUNC) &_canhrActi_rolling_max_cpp, 2},
    {"_canhrActi_rolling_min_cpp", (DL_FUNC) &_canhrActi_rolling_min_cpp, 2},
    {"_canhrActi_calculate_all_circadian_cpp", (DL_FUNC) &_canhrActi_calculate_all_circadian_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_canhrActi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
