# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

classify_intensity_cpp <- function(counts, sedentary_threshold = 100L, light_threshold = 1952L, moderate_threshold = 5725L, vigorous_threshold = 9498L) {
    .Call(`_canhrActi_classify_intensity_cpp`, counts, sedentary_threshold, light_threshold, moderate_threshold, vigorous_threshold)
}

detect_mvpa_bouts_cpp <- function(counts, moderate_threshold = 1952L, min_bout_length = 10L, drop_time = 2L, use_80_percent_rule = FALSE) {
    .Call(`_canhrActi_detect_mvpa_bouts_cpp`, counts, moderate_threshold, min_bout_length, drop_time, use_80_percent_rule)
}

detect_sedentary_bouts_cpp <- function(counts, sedentary_threshold = 100L, min_bout_length = 1L, wear = integer()) {
    .Call(`_canhrActi_detect_sedentary_bouts_cpp`, counts, sedentary_threshold, min_bout_length, wear)
}

calculate_transition_probabilities_cpp <- function(counts, sedentary_threshold = 100L, wear = integer()) {
    .Call(`_canhrActi_calculate_transition_probabilities_cpp`, counts, sedentary_threshold, wear)
}

calculate_w50_cpp <- function(bout_lengths) {
    .Call(`_canhrActi_calculate_w50_cpp`, bout_lengths)
}

calculate_gini_cpp <- function(bout_lengths) {
    .Call(`_canhrActi_calculate_gini_cpp`, bout_lengths)
}

calculate_alpha_robust_cpp <- function(bout_lengths, xmin = 1L) {
    .Call(`_canhrActi_calculate_alpha_robust_cpp`, bout_lengths, xmin)
}

estimate_xmin_cpp <- function(bout_lengths) {
    .Call(`_canhrActi_estimate_xmin_cpp`, bout_lengths)
}

sedentary_fragmentation_all_cpp <- function(counts, sedentary_threshold = 100L, wear = integer()) {
    .Call(`_canhrActi_sedentary_fragmentation_all_cpp`, counts, sedentary_threshold, wear)
}

bout_summary_by_day_cpp <- function(counts, day_indices, sedentary_threshold = 100L, moderate_threshold = 1952L) {
    .Call(`_canhrActi_bout_summary_by_day_cpp`, counts, day_indices, sedentary_threshold, moderate_threshold)
}

#' Calculate Intensity Gradient (C++ Implementation)
#'
#' High-performance calculation of the intensity gradient using log-log
#' linear regression on acceleration bin data.
#'
#' @param data NumericVector of acceleration values in mg
#' @param epoch_length Epoch length in seconds (default: 5)
#' @param bin_size Bin width in mg (default: 25)
#' @param max_value Maximum value for binning (default: 4000)
#'
#' @return List with gradient, intercept, r_squared, average_acceleration
#'
#' @keywords internal
intensity_gradient_cpp <- function(data, epoch_length = 5.0, bin_size = 25.0, max_value = 4000.0) {
    .Call(`_canhrActi_intensity_gradient_cpp`, data, epoch_length, bin_size, max_value)
}

#' Calculate MX Metrics (C++ Implementation)
#'
#' High-performance calculation of MX metrics (acceleration exceeded during
#' most active X minutes).
#'
#' @param data NumericVector of acceleration values in mg
#' @param X_values IntegerVector of time values in minutes (e.g., c(2, 5, 10, 30, 60))
#' @param epoch_length Epoch length in seconds (default: 5)
#'
#' @return Named NumericVector of MX values
#'
#' @keywords internal
calculate_MX_cpp <- function(data, X_values, epoch_length = 5.0) {
    .Call(`_canhrActi_calculate_MX_cpp`, data, X_values, epoch_length)
}

#' Calculate Complete Activity Profile (C++ Implementation)
#'
#' Combines intensity gradient and MX metrics in a single optimized function.
#'
#' @param data NumericVector of acceleration values in mg
#' @param epoch_length Epoch length in seconds
#' @param bin_size Bin size for intensity gradient
#' @param X_values X values for MX metrics
#'
#' @return List with all activity profile metrics
#'
#' @keywords internal
activity_profile_cpp <- function(data, epoch_length = 5.0, bin_size = 25.0, X_values = as.integer( c(2, 5, 10, 15, 30, 60, 120))) {
    .Call(`_canhrActi_activity_profile_cpp`, data, epoch_length, bin_size, X_values)
}

#' Create Acceleration Histogram for Intensity Gradient
#'
#' Creates binned distribution of acceleration values for intensity gradient
#' analysis or visualization.
#'
#' @param data NumericVector of acceleration values in mg
#' @param bin_size Bin width in mg (default: 25)
#' @param max_value Maximum value for regular bins (default: 4000)
#'
#' @return DataFrame with bin_lower, bin_upper, midpoint, count
#'
#' @keywords internal
acceleration_histogram_cpp <- function(data, bin_size = 25.0, max_value = 4000.0) {
    .Call(`_canhrActi_acceleration_histogram_cpp`, data, bin_size, max_value)
}

#' Calculate Acceleration Percentiles
#'
#' Fast percentile calculation for acceleration distribution.
#'
#' @param data NumericVector of acceleration values
#' @param probs NumericVector of probabilities (0-1)
#'
#' @return NumericVector of percentile values
#'
#' @keywords internal
acceleration_percentiles_cpp <- function(data, probs) {
    .Call(`_canhrActi_acceleration_percentiles_cpp`, data, probs)
}

cole_kripke_cpp <- function(counts, threshold = 1.0, apply_rescoring = TRUE) {
    .Call(`_canhrActi_cole_kripke_cpp`, counts, threshold, apply_rescoring)
}

webster_rescoring_cpp <- function(sleep) {
    .Call(`_canhrActi_webster_rescoring_cpp`, sleep)
}

sadeh_cpp <- function(counts, threshold = -4.0) {
    .Call(`_canhrActi_sadeh_cpp`, counts, threshold)
}

tudor_locke_cpp <- function(counts, sleep_threshold = 20L, min_sleep_block = 160L, max_wake_block = 60L) {
    .Call(`_canhrActi_tudor_locke_cpp`, counts, sleep_threshold, min_sleep_block, max_wake_block)
}

detect_sleep_period_cpp <- function(sleep, min_sleep_duration = 30L, sleep_onset_buffer = 5L, wake_buffer = 5L) {
    .Call(`_canhrActi_detect_sleep_period_cpp`, sleep, min_sleep_duration, sleep_onset_buffer, wake_buffer)
}

calculate_sleep_metrics_cpp <- function(sleep, sleep_onset, wake_time) {
    .Call(`_canhrActi_calculate_sleep_metrics_cpp`, sleep, sleep_onset, wake_time)
}

calculate_sri_cpp <- function(sleep_matrix) {
    .Call(`_canhrActi_calculate_sri_cpp`, sleep_matrix)
}

calculate_sri_vector_cpp <- function(sleep, epochs_per_day) {
    .Call(`_canhrActi_calculate_sri_vector_cpp`, sleep, epochs_per_day)
}

sleep_summary_by_night_cpp <- function(sleep, night_indices, counts) {
    .Call(`_canhrActi_sleep_summary_by_night_cpp`, sleep, night_indices, counts)
}

sliding_window_mean_cpp <- function(x, window_size) {
    .Call(`_canhrActi_sliding_window_mean_cpp`, x, window_size)
}

calculate_L5_M10_cpp <- function(minute_data, window_L5 = 300L, window_M10 = 600L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_L5_M10_cpp`, minute_data, window_L5, window_M10, start_minute)
}

calculate_L1_M1_cpp <- function(minute_data) {
    .Call(`_canhrActi_calculate_L1_M1_cpp`, minute_data)
}

calculate_IS_cpp <- function(hourly_data, hours_per_day = 24L) {
    .Call(`_canhrActi_calculate_IS_cpp`, hourly_data, hours_per_day)
}

calculate_IV_cpp <- function(hourly_data) {
    .Call(`_canhrActi_calculate_IV_cpp`, hourly_data)
}

calculate_phi_cpp <- function(x, lag = 1L) {
    .Call(`_canhrActi_calculate_phi_cpp`, x, lag)
}

rolling_mean_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_mean_cpp`, x, window)
}

rolling_sd_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sd_cpp`, x, window)
}

rolling_sum_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sum_cpp`, x, window)
}

rolling_max_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_max_cpp`, x, window)
}

rolling_min_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_min_cpp`, x, window)
}

calculate_all_circadian_cpp <- function(minute_data, hours_per_day = 24L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_all_circadian_cpp`, minute_data, hours_per_day, start_minute)
}

detect_wear_core_cpp <- function(counts, window_minutes, spike_tolerance_minutes, spike_max_count, use_upstream_downstream, upstream_minutes, downstream_minutes) {
    .Call(`_canhrActi_detect_wear_core_cpp`, counts, window_minutes, spike_tolerance_minutes, spike_max_count, use_upstream_downstream, upstream_minutes, downstream_minutes)
}

wear_troiano_cpp <- function(counts, window_minutes = 60L, spike_tolerance = 2L, spike_max_count = 100L) {
    .Call(`_canhrActi_wear_troiano_cpp`, counts, window_minutes, spike_tolerance, spike_max_count)
}

wear_choi_cpp <- function(counts, window_minutes = 90L, spike_tolerance = 2L, spike_max_count = 100L, upstream_minutes = 30L, downstream_minutes = 30L) {
    .Call(`_canhrActi_wear_choi_cpp`, counts, window_minutes, spike_tolerance, spike_max_count, upstream_minutes, downstream_minutes)
}

wear_canhr2025_cpp <- function(counts, window_minutes = 120L, spike_tolerance = 3L, spike_max_count = 150L, upstream_minutes = 45L, downstream_minutes = 45L) {
    .Call(`_canhrActi_wear_canhr2025_cpp`, counts, window_minutes, spike_tolerance, spike_max_count, upstream_minutes, downstream_minutes)
}

wear_triaxial_cpp <- function(axis1, axis2, axis3, window_minutes = 90L, spike_tolerance = 2L, sd_threshold = 3.0) {
    .Call(`_canhrActi_wear_triaxial_cpp`, axis1, axis2, axis3, window_minutes, spike_tolerance, sd_threshold)
}

wear_summary_cpp <- function(wear, epochs_per_hour = 60L, min_wear_hours = 10L) {
    .Call(`_canhrActi_wear_summary_cpp`, wear, epochs_per_hour, min_wear_hours)
}

get_wear_periods_cpp <- function(wear, min_duration_epochs = 1L) {
    .Call(`_canhrActi_get_wear_periods_cpp`, wear, min_duration_epochs)
}

wear_by_day_cpp <- function(wear, day_indices, epochs_per_hour = 60L, min_wear_hours = 10L) {
    .Call(`_canhrActi_wear_by_day_cpp`, wear, day_indices, epochs_per_hour, min_wear_hours)
}

