# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gt3x_log_index_cpp <- function(path) {
    .Call(`_canhrActi_gt3x_log_index_cpp`, path)
}

gt3x_log_block_cpp <- function(path, off, ts, sf, scale, start) {
    .Call(`_canhrActi_gt3x_log_block_cpp`, path, off, ts, sf, scale, start)
}

gt3x_copy_stored_cpp <- function(src, dst, offset, len) {
    .Call(`_canhrActi_gt3x_copy_stored_cpp`, src, dst, offset, len)
}

calculate_L5_M10_cpp <- function(minute_data, window_L5 = 300L, window_M10 = 600L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_L5_M10_cpp`, minute_data, window_L5, window_M10, start_minute)
}

calculate_IS_cpp <- function(hourly_data, hours_per_day = 24L) {
    .Call(`_canhrActi_calculate_IS_cpp`, hourly_data, hours_per_day)
}

calculate_IV_cpp <- function(hourly_data) {
    .Call(`_canhrActi_calculate_IV_cpp`, hourly_data)
}

rolling_mean_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_mean_cpp`, x, window)
}

rolling_sd_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sd_cpp`, x, window)
}

rolling_sum_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sum_cpp`, x, window)
}

calculate_all_circadian_cpp <- function(minute_data, hours_per_day = 24L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_all_circadian_cpp`, minute_data, hours_per_day, start_minute)
}

