# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sliding_window_mean_cpp <- function(x, window_size) {
    .Call(`_canhrActi_sliding_window_mean_cpp`, x, window_size)
}

calculate_L5_M10_cpp <- function(minute_data, window_L5 = 300L, window_M10 = 600L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_L5_M10_cpp`, minute_data, window_L5, window_M10, start_minute)
}

calculate_L1_M1_cpp <- function(minute_data) {
    .Call(`_canhrActi_calculate_L1_M1_cpp`, minute_data)
}

calculate_IS_cpp <- function(hourly_data, hours_per_day = 24L) {
    .Call(`_canhrActi_calculate_IS_cpp`, hourly_data, hours_per_day)
}

calculate_IV_cpp <- function(hourly_data) {
    .Call(`_canhrActi_calculate_IV_cpp`, hourly_data)
}

calculate_phi_cpp <- function(x, lag = 1L) {
    .Call(`_canhrActi_calculate_phi_cpp`, x, lag)
}

rolling_mean_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_mean_cpp`, x, window)
}

rolling_sd_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sd_cpp`, x, window)
}

rolling_sum_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_sum_cpp`, x, window)
}

rolling_max_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_max_cpp`, x, window)
}

rolling_min_cpp <- function(x, window) {
    .Call(`_canhrActi_rolling_min_cpp`, x, window)
}

calculate_all_circadian_cpp <- function(minute_data, hours_per_day = 24L, start_minute = 0L) {
    .Call(`_canhrActi_calculate_all_circadian_cpp`, minute_data, hours_per_day, start_minute)
}

